replace debuginfo flags with release profile
We need to generate debuginfo or else the rpm build will fail, but
passing this through compiler flag overrides can cause some crates
to fail to build with the following error.

  error: -g and -C debuginfo both provided

Instead we can add a release profile to our first party crates to
ensure that we include debuginfo.

Signed-off-by: Ben Cressey <bcressey@amazon.com>